Dry up types and pragmas
status-im/nim-rocksdb pull request #8
Opened 2018-07-30 09:16 UTC by yglukhov

1. Types changed from objects to ptr objects. This addresses `{.incompleteStruct.}` concern.
2. Pragma `{.cdecl, importc: "foo", dynlib: librocksdb.}` is replaced with `{.importrocks.}`. Had to use vim for that :).

2018-07-30 09:51 UTC, mratsim approved these changes
LGTM,

Can you update the example as well.

I suppose Nimbus RocksDB also has to be updated.

2018-07-30 09:58 UTC, yglukhov commented
Example updated. Nimbus is fine, it uses higher level api.

2018-07-30 16:10 UTC, arnetheduck requested changes
without `incompleteStruct`, you can still derefererence the type (in some generic code for example) and end up with an invalid sizeof.. in `c`, this is the difference between a forward decl and an empty struct.. using the former prevents some mistakes common with opaque pointer types

2018-07-30 16:37 UTC, yglukhov commented
@arnetheduck `{.incomleteStruct.}` will prevent you from dereferencing only is used along with `header` pragma, in which case the error will be reported by the C compiler, not Nim. `distinct pointer` + `isNil {.borrow.}` would be closer to what you want, which I've just committed. I still think that's overengineering, but whatever.

2018-08-02 12:47 UTC, arnetheduck approved these changes

2018-08-02 12:51 UTC, merged